package com.yuntao.zhushou.zplugin.ui;

import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.yuntao.zhushou.model.domain.codeBuild.Property;
import com.yuntao.zhushou.model.param.codeBuild.EntityParam;
import com.yuntao.zhushou.zplugin.ActionManager;
import com.yuntao.zhushou.zplugin.AnalyseModelUtils;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

//import java.awt.event.ActionEvent;

//import java.awt.event.ActionEvent;

//import java.awt.event.import com.intellij.openapi.actionSystem.AnActionEvent;ActionEvent;

//import java.awt.event.ActionEvent;


/**
 * Created by shan on 2017/9/7.
 */
public class FieldSelForm {
    private JPanel mainPanel;
    private JList listMethod;
    private JButton btnExecute;
    private JButton btnCancel;

    private AnActionEvent event;

    private EntityParam entityParam;


    public FieldSelForm(final AnActionEvent event) {
        this.event = event;
        btnExecute.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                AnalyseModelUtils.analyseProperty(event);
//                ListSelectionModel selectionModel = listMethod.getSelectionModel();
                List<Property> selectedValuesList = listMethod.getSelectedValuesList();

                if (selectedValuesList == null) {
                    throw new RuntimeException("请选择要您要操作的项");
                }
                entityParam.setPropertyList(selectedValuesList);
                ActionManager actionManager = new ActionManager();
                if (event.getPresentation().getText().equals("新建实体")) {
                    String projectFilePath = event.getProject().getBasePath();
                    actionManager.newEntity(projectFilePath, entityParam);
                }


            }

        });
        btnCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //update

            }
        });
    }

    public void start(String title) {
        JFrame frame = new JFrame(title);
        frame.setContentPane(this.mainPanel);
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
//        frame.setLocationByPlatform(true);
        frame.pack();

        frame.setLocationRelativeTo(null);
        frame.setSize(270, 450);
//        frame.setSize(600,500);
//        frame.setExtendedState(Frame.MAXIMIZED_BOTH);
        frame.setLocationByPlatform(true);
        frame.setVisible(true);

//        Vector<Object> objects = new Vector<>();
        DefaultListModel listModel = new DefaultListModel();

        entityParam = AnalyseModelUtils.analyseProperty(this.event);
        if (entityParam != null && entityParam.getPropertyList() != null) {
            for (Property property : entityParam.getPropertyList()) {
//                StringBuilder sb = new StringBuilder();
//                sb.append(property.getEnName());
//                sb.append(":");
//                sb.append(property.getCnName());
//                sb.append(" [" + property.getDataType() + ":" + (StringUtils.isNotEmpty(property.getLength()) ? property.getLength() : "") + "]");
//                objects.add(sb.toString());
                listModel.addElement(property);
            }
        }
//        listMethod.setListData(objects);
        listMethod.setModel(listModel);

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "属性选择", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.TOP));
        listMethod = new JList();
        listMethod.setAlignmentX(1.0f);
        listMethod.setAlignmentY(1.0f);
        listMethod.setFont(UIManager.getFont("ColorChooser.font"));
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("111");
        defaultListModel1.addElement("2222");
        listMethod.setModel(defaultListModel1);
        listMethod.setVisibleRowCount(15);
        mainPanel.add(listMethod, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnExecute = new JButton();
        btnExecute.setText("执行");
        panel1.add(btnExecute, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCancel = new JButton();
        btnCancel.setText("取消");
        panel1.add(btnCancel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
